management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  hystrix:
    enabled: false

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

